version: '3.8'

services:
  hexadash:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_DATABASE: postgres
      DB_PASSWORD: mysecretpassword
      DB_PORT: 5432

  db:
    image: postgres:16
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./data-sample.sql:/docker-entrypoint-initdb.d/data-sample.sql
      # - postgres_data:/var/lib/postgresql/data (commented out to disable persistent data)

#volumes:
#  postgres_data: (commented out to disable persistent volume)
